"""empty message

Revision ID: 4de072f7bd30
Revises: c99a148ed72b
Create Date: 2021-03-25 14:40:08.710798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4de072f7bd30'
down_revision = 'c99a148ed72b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zealidentifier', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('zealidentifier', sa.Column('version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zealidentifier', 'version')
    op.drop_column('zealidentifier', 'created_on')
    # ### end Alembic commands ###
