"""empty message

Revision ID: 4eaef63a4484
Revises: 4de072f7bd30
Create Date: 2021-03-25 17:36:13.619837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eaef63a4484'
down_revision = '4de072f7bd30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zealidentifier', sa.Column('prefix', sa.String(), nullable=True))
    op.create_index(op.f('ix_zealidentifier_prefix'), 'zealidentifier', ['prefix'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zealidentifier_prefix'), table_name='zealidentifier')
    op.drop_column('zealidentifier', 'prefix')
    # ### end Alembic commands ###
