"""empty message

Revision ID: 586204c565f5
Revises: 4eaef63a4484
Create Date: 2021-09-30 17:50:49.220643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '586204c565f5'
down_revision = '4eaef63a4484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
