"""zeal pool

Revision ID: 5a92d5a98c7e
Revises: ed8d3036894b
Create Date: 2021-09-30 18:14:50.214673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a92d5a98c7e'
down_revision = 'ed8d3036894b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zealidentifier', sa.Column('pool', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zealidentifier', 'pool')
    # ### end Alembic commands ###
