"""empty message

Revision ID: c99a148ed72b
Revises: f4bf0e452fab
Create Date: 2021-03-25 14:33:51.395014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c99a148ed72b'
down_revision = 'f4bf0e452fab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
