"""empty message

Revision ID: ed8d3036894b
Revises: 586204c565f5
Create Date: 2021-09-30 17:52:54.556045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed8d3036894b'
down_revision = '586204c565f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zealidentifier', sa.Column('linkage_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zealidentifier', 'linkage_id')
    # ### end Alembic commands ###
