"""empty message

Revision ID: f4bf0e452fab
Revises: 
Create Date: 2021-03-25 13:43:05.431232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4bf0e452fab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zealidentifier',
    sa.Column('zeal', sa.String(), nullable=False),
    sa.Column('is_assigned', sa.Boolean(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('assigned_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('zeal')
    )
    op.create_index(op.f('ix_zealidentifier_zeal'), 'zealidentifier', ['zeal'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zealidentifier_zeal'), table_name='zealidentifier')
    op.drop_table('zealidentifier')
    # ### end Alembic commands ###
